change ext trigger to worflow_run

diff --git a/.github/workflows/container-build.yml b/.github/workflows/container-build.yml
--- a/.github/workflows/container-build.yml
+++ b/.github/workflows/container-build.yml
@@ -3,11 +3,24 @@ name: Build and Publish nginx Container Image
 on:
   push:
     branches: [main]
-  # Trigger workflow from external sources
-  repository_dispatch:
-    types: [frontend-updated]
+  workflow_run:
+    # Triggered by subsystem worflows
+    workflows: ["Build Frontend"]
+    types:
+    - completed
+    branches: [main]
 
 jobs:
+  check-status:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check triggering workflow status
+        run: |
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "Previous workflow failed. Exiting..."
+            exit 1
+          fi
+
   build-and-push:
     runs-on: ubuntu-latest
 
